// <auto-generated />
using System;
using FudbalskiKlub.Services.Database1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FudbalskiKlub.Services.Migrations
{
    [DbContext(typeof(MiniafkContext))]
    partial class MiniafkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Bolest", b =>
                {
                    b.Property<int>("BolestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolestId"));

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<string>("SifraPovrede")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipPovrede")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TrajanjePovredeDani")
                        .HasColumnType("int");

                    b.HasKey("BolestId")
                        .HasName("PK__Bolest__345EDD63C1FF3573");

                    b.ToTable("Bolest", (string)null);

                    b.HasData(
                        new
                        {
                            BolestId = 1,
                            Izbrisan = false,
                            SifraPovrede = "RK1",
                            TipPovrede = "Prijelom koljena",
                            TrajanjePovredeDani = 30
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Clanarina", b =>
                {
                    b.Property<int>("ClanarinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClanarinaId"));

                    b.Property<DateTime?>("DatumPlacanja")
                        .HasColumnType("datetime");

                    b.Property<double?>("Dug")
                        .HasColumnType("float");

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<double?>("IznosClanarine")
                        .HasColumnType("float");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<bool?>("Placena")
                        .HasColumnType("bit");

                    b.HasKey("ClanarinaId")
                        .HasName("PK__Clanarin__C51E3B9744FDF577");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Clanarina", (string)null);

                    b.HasData(
                        new
                        {
                            ClanarinaId = 1,
                            DatumPlacanja = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(4037),
                            Dug = 0.0,
                            Izbrisan = false,
                            IznosClanarine = 60.0,
                            KorisnikId = 4,
                            Placena = false
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LozinkaHash")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LozinkaSalt")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("PodUgovorom")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PodUgovoromDo")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("PodUgovoromOd")
                        .HasColumnType("datetime");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StrucnaSprema")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Uloga")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("KorisnikId")
                        .HasName("PK__Korisnik__80B06D41D28B3EED");

                    b.ToTable("Korisnik", (string)null);

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            DatumRodjenja = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ajdinaganovic23@gmail.com",
                            Ime = "Ajdin",
                            Izbrisan = false,
                            KorisnickoIme = "ajdo",
                            LozinkaHash = "A8p5Z0J5Vpk3+xijG+CIEWHHclU=",
                            LozinkaSalt = "WPF5nHZxfUk1ewO0N0qBPA==",
                            PodUgovorom = true,
                            PodUgovoromDo = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PodUgovoromOd = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(3038),
                            Prezime = "Admin",
                            StrucnaSprema = "VSS",
                            Uloga = "Administrator"
                        },
                        new
                        {
                            KorisnikId = 2,
                            DatumRodjenja = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "trener1@gmail.com",
                            Ime = "Glavni",
                            Izbrisan = false,
                            KorisnickoIme = "trener1",
                            LozinkaHash = "HTDgpKHNsBM5C0i9i9nkXnbOXxk=",
                            LozinkaSalt = "ZMafeiMJmeJzqEJwNeYG6g==",
                            PodUgovorom = true,
                            PodUgovoromDo = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PodUgovoromOd = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(3491),
                            Prezime = "Trener",
                            StrucnaSprema = "VSS",
                            Uloga = "Glavni trener"
                        },
                        new
                        {
                            KorisnikId = 3,
                            DatumRodjenja = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "doktor1@gmail.com",
                            Ime = "Glavni",
                            Izbrisan = false,
                            KorisnickoIme = "doktor1",
                            LozinkaHash = "vraCTh2U92Oh6Vn/HMpccpLICbM=",
                            LozinkaSalt = "m3hm584IVgX1DS4IQIekSA==",
                            PodUgovorom = true,
                            PodUgovoromDo = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PodUgovoromOd = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(3547),
                            Prezime = "Doktor",
                            StrucnaSprema = "VSS",
                            Uloga = "Doktor"
                        },
                        new
                        {
                            KorisnikId = 4,
                            DatumRodjenja = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "igrac1@gmail.com",
                            Ime = "Igrac",
                            Izbrisan = false,
                            KorisnickoIme = "igrac1",
                            LozinkaHash = "NFMrVzEpb/DnvxH0lRZyjfzmRag=",
                            LozinkaSalt = "tuIaDWPEdQSOEVwNrpQFSA==",
                            PodUgovorom = true,
                            PodUgovoromDo = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PodUgovoromOd = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(3590),
                            Prezime = "Prvi",
                            StrucnaSprema = "SSS",
                            Uloga = "Igrac"
                        },
                        new
                        {
                            KorisnikId = 5,
                            DatumRodjenja = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kupac1@gmail.com",
                            Ime = "Kupac",
                            Izbrisan = false,
                            KorisnickoIme = "kupac1",
                            LozinkaHash = "nrPagCSgYHf3U9oNMoflRQFOva4=",
                            LozinkaSalt = "FTpVTGzhfJunpqzEKHCrlA==",
                            PodUgovorom = true,
                            PodUgovoromDo = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PodUgovoromOd = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(3629),
                            Prezime = "Prvi",
                            StrucnaSprema = "VSS",
                            Uloga = "Kupac"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.KorisnikBolest", b =>
                {
                    b.Property<int>("KorisnikBolestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikBolestId"));

                    b.Property<int>("BolestId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikBolestId")
                        .HasName("PK__Korisnik__8ECF77DF3087028A");

                    b.HasIndex("BolestId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("KorisnikBolest", (string)null);
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.KorisnikPozicija", b =>
                {
                    b.Property<int>("KorisnikPozicijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikPozicijaId"));

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("PozicijaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikPozicijaId")
                        .HasName("PK__Korisnik__F374D25700F98E73");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PozicijaId");

                    b.ToTable("KorisnikPozicija", (string)null);

                    b.HasData(
                        new
                        {
                            KorisnikPozicijaId = 1,
                            KorisnikId = 4,
                            PozicijaId = 1
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.KorisnikTransakcijskiRacun", b =>
                {
                    b.Property<int>("KorisnikTransakcijskiRacunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikTransakcijskiRacunId"));

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("TransakcijskiRacunId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikTransakcijskiRacunId")
                        .HasName("PK__Korisnik__1608726E51D03733");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("TransakcijskiRacunId");

                    b.ToTable("KorisnikTransakcijskiRacun", (string)null);
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.KorisnikUloga", b =>
                {
                    b.Property<int>("KorisnikUlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikUlogaId"));

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikUlogaId")
                        .HasName("PK__Korisnik__1608726E78CD53A3");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisnikUloga", (string)null);
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Narudzba", b =>
                {
                    b.Property<int>("NarudzbaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NarudzbaId"));

                    b.Property<string>("BrojNarudzba")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("NarudzbaId")
                        .HasName("PK__Narudzba__FBEC1377D43365F9");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Narudzba", (string)null);

                    b.HasData(
                        new
                        {
                            NarudzbaId = 1,
                            BrojNarudzba = "AJSDJWAIAfasfh1h23hs",
                            Datum = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(4207),
                            KorisnikId = 5,
                            Status = "kreirano"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.NarudzbaStavke", b =>
                {
                    b.Property<int>("NarudzbaStavkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NarudzbaStavkeId"));

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbaId")
                        .HasColumnType("int");

                    b.Property<int?>("ProizvodId")
                        .HasColumnType("int");

                    b.HasKey("NarudzbaStavkeId")
                        .HasName("PK__Narudzba__7DC8EFED3DA2E1FE");

                    b.HasIndex("NarudzbaId");

                    b.HasIndex("ProizvodId");

                    b.ToTable("NarudzbaStavke", (string)null);

                    b.HasData(
                        new
                        {
                            NarudzbaStavkeId = 1,
                            Kolicina = 2,
                            NarudzbaId = 1,
                            ProizvodId = 1
                        },
                        new
                        {
                            NarudzbaStavkeId = 2,
                            Kolicina = 1,
                            NarudzbaId = 1,
                            ProizvodId = 3
                        },
                        new
                        {
                            NarudzbaStavkeId = 3,
                            Kolicina = 20,
                            NarudzbaId = 1,
                            ProizvodId = 4
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Platum", b =>
                {
                    b.Property<int>("PlataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlataId"));

                    b.Property<DateTime?>("DatumSlanja")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<double?>("Iznos")
                        .HasColumnType("float");

                    b.Property<string>("StateMachine")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TransakcijskiRacunId")
                        .HasColumnType("int");

                    b.HasKey("PlataId")
                        .HasName("PK__Plata__373F7313BACBD819");

                    b.HasIndex("TransakcijskiRacunId");

                    b.ToTable("Plata");

                    b.HasData(
                        new
                        {
                            PlataId = 1,
                            DatumSlanja = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(4321),
                            Izbrisan = false,
                            Iznos = 1200.0,
                            StateMachine = "active",
                            TransakcijskiRacunId = 1
                        },
                        new
                        {
                            PlataId = 2,
                            DatumSlanja = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(4328),
                            Izbrisan = false,
                            Iznos = 900.0,
                            StateMachine = "active",
                            TransakcijskiRacunId = 2
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Pozicija", b =>
                {
                    b.Property<int>("PozicijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PozicijaId"));

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<string>("KategorijaPozicije")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NazivPozicije")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PozicijaId")
                        .HasName("PK__Pozicija__C25169AEA95BEC4D");

                    b.ToTable("Pozicija", (string)null);

                    b.HasData(
                        new
                        {
                            PozicijaId = 1,
                            Izbrisan = false,
                            KategorijaPozicije = "Napad",
                            NazivPozicije = "Centarfor"
                        },
                        new
                        {
                            PozicijaId = 2,
                            Izbrisan = false,
                            KategorijaPozicije = "Vezni red",
                            NazivPozicije = "Srednji vezni"
                        },
                        new
                        {
                            PozicijaId = 3,
                            Izbrisan = false,
                            KategorijaPozicije = "Odbrana",
                            NazivPozicije = "Srednji stoper"
                        },
                        new
                        {
                            PozicijaId = 4,
                            Izbrisan = false,
                            KategorijaPozicije = "Vezni red",
                            NazivPozicije = "Ofanzivni vezni"
                        },
                        new
                        {
                            PozicijaId = 5,
                            Izbrisan = false,
                            KategorijaPozicije = "Odbrana",
                            NazivPozicije = "Golman"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Proizvod", b =>
                {
                    b.Property<int>("ProizvodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodId"));

                    b.Property<double?>("Cijena")
                        .HasColumnType("float");

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<string>("Kategorija")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sifra")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProizvodId")
                        .HasName("PK__Proizvod__21A8BFF81155EE96");

                    b.ToTable("Proizvod", (string)null);

                    b.HasData(
                        new
                        {
                            ProizvodId = 1,
                            Cijena = 55.0,
                            Izbrisan = false,
                            Kategorija = "Dresovi",
                            Kolicina = 50,
                            Naziv = "Gostujuci dres 24/25",
                            Sifra = "GD2425",
                            StateMachine = "draft"
                        },
                        new
                        {
                            ProizvodId = 2,
                            Cijena = 55.0,
                            Izbrisan = false,
                            Kategorija = "Dresovi",
                            Kolicina = 50,
                            Naziv = "Domaci dres 24/25",
                            Sifra = "DD2425",
                            StateMachine = "draft"
                        },
                        new
                        {
                            ProizvodId = 3,
                            Cijena = 25.0,
                            Izbrisan = false,
                            Kategorija = "Dodaci",
                            Kolicina = 150,
                            Naziv = "Sal",
                            Sifra = "Sal2425",
                            StateMachine = "draft"
                        },
                        new
                        {
                            ProizvodId = 4,
                            Cijena = 1.0,
                            Izbrisan = false,
                            Kategorija = "Razno",
                            Kolicina = 1000,
                            Naziv = "Fudbalske slicice (5 kom.)",
                            Sifra = "FS2425",
                            StateMachine = "draft"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Stadion", b =>
                {
                    b.Property<int>("StadionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StadionId"));

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<int?>("KapacitetStadiona")
                        .HasColumnType("int");

                    b.Property<string>("NazivStadiona")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StadionId")
                        .HasName("PK__Stadion__DDB3F389E8282FAE");

                    b.ToTable("Stadion", (string)null);

                    b.HasData(
                        new
                        {
                            StadionId = 1,
                            Izbrisan = false,
                            KapacitetStadiona = 2000,
                            NazivStadiona = "Podbrdo"
                        },
                        new
                        {
                            StadionId = 2,
                            Izbrisan = false,
                            KapacitetStadiona = 2000,
                            NazivStadiona = "Uzbrdo"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Statistika", b =>
                {
                    b.Property<int>("StatistikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatistikaId"));

                    b.Property<int?>("Asistencije")
                        .HasColumnType("int");

                    b.Property<int?>("BezPrimGola")
                        .HasColumnType("int");

                    b.Property<int?>("CrveniKartoni")
                        .HasColumnType("int");

                    b.Property<int?>("Golovi")
                        .HasColumnType("int");

                    b.Property<bool?>("IgracMjeseca")
                        .HasColumnType("bit");

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<double?>("OcjenaZadUtak")
                        .HasColumnType("float");

                    b.Property<double?>("ProsjecnaOcjena")
                        .HasColumnType("float");

                    b.Property<int?>("ZutiKartoni")
                        .HasColumnType("int");

                    b.HasKey("StatistikaId")
                        .HasName("PK__Statisti__B718DBB73CB4E6D2");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Statistika", (string)null);

                    b.HasData(
                        new
                        {
                            StatistikaId = 1,
                            Asistencije = 5,
                            BezPrimGola = 0,
                            CrveniKartoni = 1,
                            Golovi = 10,
                            IgracMjeseca = false,
                            Izbrisan = false,
                            KorisnikId = 4,
                            OcjenaZadUtak = 3.0,
                            ProsjecnaOcjena = 8.0,
                            ZutiKartoni = 2
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Termin", b =>
                {
                    b.Property<int>("TerminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerminId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<string>("Rezultat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SifraTermina")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("StadionId")
                        .HasColumnType("int");

                    b.Property<string>("TipTermina")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TerminId")
                        .HasName("PK__Termin__42126C95BA3670B3");

                    b.HasIndex("StadionId");

                    b.ToTable("Termin", (string)null);

                    b.HasData(
                        new
                        {
                            TerminId = 1,
                            Datum = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(4401),
                            Rezultat = "0:0",
                            SifraTermina = "UTK1",
                            StadionId = 1,
                            TipTermina = "Domaca utakmica"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.ToDo4924", b =>
                {
                    b.Property<int>("todo4924id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("todo4924id"));

                    b.Property<DateTime>("datumzavrsenja")
                        .HasColumnType("datetime");

                    b.Property<int>("korisnikid")
                        .HasColumnType("int");

                    b.Property<string>("nazivaktivnosti")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("opisaktivnosti")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("statemachine")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("todo4924id")
                        .HasName("PK_TODO4924_askdaskdj");

                    b.HasIndex("korisnikid");

                    b.ToTable("ToDo4924", (string)null);

                    b.HasData(
                        new
                        {
                            todo4924id = 1,
                            datumzavrsenja = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(4002),
                            korisnikid = 1,
                            nazivaktivnosti = "prva aktivnost",
                            opisaktivnosti = "opis prve aktivnosti",
                            statemachine = "U toku"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.TransakcijskiRacun", b =>
                {
                    b.Property<int>("TransakcijskiRacunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransakcijskiRacunId"));

                    b.Property<string>("AdresaPrebivalista")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("NazivBanke")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TransakcijskiRacunId")
                        .HasName("PK__Transakc__2F0E2ED1FF943D6E");

                    b.HasIndex("KorisnikId");

                    b.ToTable("TransakcijskiRacun", (string)null);

                    b.HasData(
                        new
                        {
                            TransakcijskiRacunId = 1,
                            AdresaPrebivalista = "Mahala b.b.",
                            BrojRacuna = "12341234",
                            Izbrisan = false,
                            KorisnikId = 1,
                            NazivBanke = "Univerzitetskih kredita"
                        },
                        new
                        {
                            TransakcijskiRacunId = 2,
                            AdresaPrebivalista = "Alipasino polje 47",
                            BrojRacuna = "47474747",
                            Izbrisan = false,
                            KorisnikId = 2,
                            NazivBanke = "Lipo halve hamdija"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Trening", b =>
                {
                    b.Property<int>("TreningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreningId"));

                    b.Property<DateTime?>("DatumTreninga")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<string>("NazivTreninga")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipTreninga")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TreningId")
                        .HasName("PK__Trening__3B04A8D37D605210");

                    b.ToTable("Trening", (string)null);

                    b.HasData(
                        new
                        {
                            TreningId = 1,
                            DatumTreninga = new DateTime(2024, 9, 16, 6, 38, 46, 694, DateTimeKind.Local).AddTicks(4427),
                            Izbrisan = false,
                            NazivTreninga = "TPT",
                            TipTreninga = "Trening prvog tipa"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.TreningStadion", b =>
                {
                    b.Property<int>("TreningStadionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreningStadionId"));

                    b.Property<int?>("StadionId")
                        .HasColumnType("int");

                    b.Property<int?>("TreningId")
                        .HasColumnType("int");

                    b.HasKey("TreningStadionId")
                        .HasName("PK__TreningS__83078871C7602F15");

                    b.HasIndex("StadionId");

                    b.HasIndex("TreningId");

                    b.ToTable("TreningStadion", (string)null);
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<bool?>("Izbrisan")
                        .HasColumnType("bit");

                    b.Property<string>("NazivUloge")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PodtipUloge")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UlogaId")
                        .HasName("PK__Uloga__DCAB23CBA0BD3CE4");

                    b.ToTable("Uloga", (string)null);

                    b.HasData(
                        new
                        {
                            UlogaId = 1,
                            Izbrisan = false,
                            NazivUloge = "Administrator",
                            PodtipUloge = "Administracija"
                        },
                        new
                        {
                            UlogaId = 2,
                            Izbrisan = false,
                            NazivUloge = "Glavni trener",
                            PodtipUloge = "Strucni stab"
                        },
                        new
                        {
                            UlogaId = 3,
                            Izbrisan = false,
                            NazivUloge = "Glavni doktor",
                            PodtipUloge = "Medicinsko osoblje"
                        },
                        new
                        {
                            UlogaId = 4,
                            Izbrisan = false,
                            NazivUloge = "Igrac",
                            PodtipUloge = "Clan"
                        },
                        new
                        {
                            UlogaId = 5,
                            Izbrisan = false,
                            NazivUloge = "Kupac",
                            PodtipUloge = "Navijac"
                        },
                        new
                        {
                            UlogaId = 6,
                            Izbrisan = false,
                            NazivUloge = "Bez uloge",
                            PodtipUloge = "Bez uloge"
                        });
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Clanarina", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Korisnik", "Korisnik")
                        .WithMany("Clanarinas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_KorisnikClanarina");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.KorisnikBolest", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Bolest", "Bolest")
                        .WithMany("KorisnikBolests")
                        .HasForeignKey("BolestId")
                        .IsRequired()
                        .HasConstraintName("FK_BolestKorisnikBolest");

                    b.HasOne("FudbalskiKlub.Services.Database1.Korisnik", "Korisnik")
                        .WithMany("KorisnikBolests")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisnikKorisnikBolest");

                    b.Navigation("Bolest");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.KorisnikPozicija", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Korisnik", "Korisnik")
                        .WithMany("KorisnikPozicijas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_KorisnikKorisnikPozicija");

                    b.HasOne("FudbalskiKlub.Services.Database1.Pozicija", "Pozicija")
                        .WithMany("KorisnikPozicijas")
                        .HasForeignKey("PozicijaId")
                        .HasConstraintName("FK_PozicijaKorisnikPozicija");

                    b.Navigation("Korisnik");

                    b.Navigation("Pozicija");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.KorisnikTransakcijskiRacun", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Korisnik", "Korisnik")
                        .WithMany("KorisnikTransakcijskiRacuns")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisnikKorisnikTransakcijskiRacun");

                    b.HasOne("FudbalskiKlub.Services.Database1.TransakcijskiRacun", "TransakcijskiRacun")
                        .WithMany("KorisnikTransakcijskiRacuns")
                        .HasForeignKey("TransakcijskiRacunId")
                        .IsRequired()
                        .HasConstraintName("FK_TransakcijskiRacunKorisnikTransakcijskiRacun");

                    b.Navigation("Korisnik");

                    b.Navigation("TransakcijskiRacun");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.KorisnikUloga", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Korisnik", "Korisnik")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisnikKorisnikUloga");

                    b.HasOne("FudbalskiKlub.Services.Database1.Uloga", "Uloga")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("UlogaId")
                        .IsRequired()
                        .HasConstraintName("FK_UlogaKorisnikUloga");

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Narudzba", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.NarudzbaStavke", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Narudzba", "Narudzba")
                        .WithMany("NarudzbaStavkes")
                        .HasForeignKey("NarudzbaId")
                        .HasConstraintName("FK_NarudzbaStavkeNarudzba");

                    b.HasOne("FudbalskiKlub.Services.Database1.Proizvod", "Proizvod")
                        .WithMany("NarudzbaStavkes")
                        .HasForeignKey("ProizvodId")
                        .HasConstraintName("FK_NarudzbaStavkeProizvod");

                    b.Navigation("Narudzba");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Platum", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.TransakcijskiRacun", "TransakcijskiRacun")
                        .WithMany("Plata")
                        .HasForeignKey("TransakcijskiRacunId")
                        .HasConstraintName("FK_TransakcijskiRacunPlata");

                    b.Navigation("TransakcijskiRacun");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Statistika", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Korisnik", "Korisnik")
                        .WithMany("Statistikas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_KorisnikStatistika");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Termin", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Stadion", "Stadion")
                        .WithMany("Termins")
                        .HasForeignKey("StadionId")
                        .HasConstraintName("FK_StadionTermin");

                    b.Navigation("Stadion");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.ToDo4924", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Korisnik", "Korisnik")
                        .WithMany("ToDo4924s")
                        .HasForeignKey("korisnikid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ToDo4924Korisnik");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.TransakcijskiRacun", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Korisnik", "Korisnik")
                        .WithMany("TransakcijskiRacuns")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_KorisnikTransakcijski");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.TreningStadion", b =>
                {
                    b.HasOne("FudbalskiKlub.Services.Database1.Stadion", "Stadion")
                        .WithMany("TreningStadions")
                        .HasForeignKey("StadionId")
                        .HasConstraintName("FK_StadionTreningStadion");

                    b.HasOne("FudbalskiKlub.Services.Database1.Trening", "Trening")
                        .WithMany("TreningStadions")
                        .HasForeignKey("TreningId")
                        .HasConstraintName("FK_TreningTreningStadion");

                    b.Navigation("Stadion");

                    b.Navigation("Trening");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Bolest", b =>
                {
                    b.Navigation("KorisnikBolests");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Korisnik", b =>
                {
                    b.Navigation("Clanarinas");

                    b.Navigation("KorisnikBolests");

                    b.Navigation("KorisnikPozicijas");

                    b.Navigation("KorisnikTransakcijskiRacuns");

                    b.Navigation("KorisnikUlogas");

                    b.Navigation("Statistikas");

                    b.Navigation("ToDo4924s");

                    b.Navigation("TransakcijskiRacuns");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Narudzba", b =>
                {
                    b.Navigation("NarudzbaStavkes");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Pozicija", b =>
                {
                    b.Navigation("KorisnikPozicijas");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Proizvod", b =>
                {
                    b.Navigation("NarudzbaStavkes");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Stadion", b =>
                {
                    b.Navigation("Termins");

                    b.Navigation("TreningStadions");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.TransakcijskiRacun", b =>
                {
                    b.Navigation("KorisnikTransakcijskiRacuns");

                    b.Navigation("Plata");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Trening", b =>
                {
                    b.Navigation("TreningStadions");
                });

            modelBuilder.Entity("FudbalskiKlub.Services.Database1.Uloga", b =>
                {
                    b.Navigation("KorisnikUlogas");
                });
#pragma warning restore 612, 618
        }
    }
}
